==================================================
Metodo: SaveOutput
Fecha: 20/04/2021 03:55:38 AM

"{\"Message\":\"No se especificó el token de seguridad\",\"Id\":0,\"IsSuccess\":false,\"UserMessage\":\"No se especificó el token de seguridad\",\"DevMessage\":\"System.Exception: No se especificó el token de seguridad\\r\\n   at Ecuafact.WebAPI.Filters.EcuafactExpressAuthorizeAttribute.OnAuthorization(HttpActionContext ActionContext)\",\"StatusCode\":\"401\",\"MoreInfo\":\"https://apides.ecuafact.com/v3/errors/401\"}"
==================================================
Metodo: SaveOutput
Fecha: 20/04/2021 03:57:01 AM

"{\"Message\":\"An exception has been raised that is likely due to a transient failure. If you are connecting to a SQL Azure database consider using SqlAzureExecutionStrategy.\",\"Id\":0,\"IsSuccess\":false,\"UserMessage\":\"An exception has been raised that is likely due to a transient failure. If you are connecting to a SQL Azure database consider using SqlAzureExecutionStrategy.\",\"DevMessage\":\"System.Data.Entity.Core.EntityException: An exception has been raised that is likely due to a transient failure. If you are connecting to a SQL Azure database consider using SqlAzureExecutionStrategy. ---> System.Data.Entity.Core.EntityException: The underlying provider failed on Open. ---> System.Data.Entity.Core.EntityException: An exception has been raised that is likely due to a transient failure. If you are connecting to a SQL Azure database consider using SqlAzureExecutionStrategy. ---> System.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the login process. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception: No process is on the other end of the pipe\\r\\n   --- End of inner exception stack trace ---\\r\\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\\r\\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\\r\\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\\r\\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\\r\\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\\r\\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\\r\\n   at System.Data.SqlClient.SqlConnection.Open()\\r\\n   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)\\r\\n   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)\\r\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass2_0.<Execute>b__0()\\r\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)\\r\\n   --- End of inner exception stack trace ---\\r\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)\\r\\n   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()\\r\\n   --- End of inner exception stack trace ---\\r\\n   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()\\r\\n   at System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)\\r\\n   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)\\r\\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__0()\\r\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)\\r\\n   --- End of inner exception stack trace ---\\r\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)\\r\\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)\\r\\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()\\r\\n   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()\\r\\n   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)\\r\\n   at Ecuafact.WebAPI.Dal.Services.RequestSessionsService.GetSessionByToken(String token)\\r\\n   at Ecuafact.WebAPI.Filters.EcuafactExpressAuthorizeAttribute.OnAuthorization(HttpActionContext ActionContext)\",\"StatusCode\":\"401\",\"MoreInfo\":\"https://apides.ecuafact.com/v3/errors/401\"}"
